//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartad) DeepCopyInto(out *AzureVMSchedulerStartad) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartad.
func (in *AzureVMSchedulerStartad) DeepCopy() *AzureVMSchedulerStartad {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartadList) DeepCopyInto(out *AzureVMSchedulerStartadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStartad, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartadList.
func (in *AzureVMSchedulerStartadList) DeepCopy() *AzureVMSchedulerStartadList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartadSpec) DeepCopyInto(out *AzureVMSchedulerStartadSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartadSpec.
func (in *AzureVMSchedulerStartadSpec) DeepCopy() *AzureVMSchedulerStartadSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartadStatus) DeepCopyInto(out *AzureVMSchedulerStartadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartadStatus.
func (in *AzureVMSchedulerStartadStatus) DeepCopy() *AzureVMSchedulerStartadStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopad) DeepCopyInto(out *AzureVMSchedulerStopad) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopad.
func (in *AzureVMSchedulerStopad) DeepCopy() *AzureVMSchedulerStopad {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopadList) DeepCopyInto(out *AzureVMSchedulerStopadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStopad, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopadList.
func (in *AzureVMSchedulerStopadList) DeepCopy() *AzureVMSchedulerStopadList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopadSpec) DeepCopyInto(out *AzureVMSchedulerStopadSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopadSpec.
func (in *AzureVMSchedulerStopadSpec) DeepCopy() *AzureVMSchedulerStopadSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopadStatus) DeepCopyInto(out *AzureVMSchedulerStopadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopadStatus.
func (in *AzureVMSchedulerStopadStatus) DeepCopy() *AzureVMSchedulerStopadStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopadStatus)
	in.DeepCopyInto(out)
	return out
}
