# permissions for end users to view awsvmschedulerstartads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmschedulerstartad-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-ad
    app.kubernetes.io/part-of: vm-scheduler-operator-ad
    app.kubernetes.io/managed-by: kustomize
  name: awsvmschedulerstartad-viewer-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartads/status
  verbs:
  - get
