# permissions for end users to view azurevmschedulerstopads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azurevmschedulerstopad-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-ad
    app.kubernetes.io/part-of: vm-scheduler-operator-ad
    app.kubernetes.io/managed-by: kustomize
  name: azurevmschedulerstopad-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopads/status
  verbs:
  - get
