# permissions for end users to view gcpvmschedulerstartads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpvmschedulerstartad-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-ad
    app.kubernetes.io/part-of: vm-scheduler-operator-ad
    app.kubernetes.io/managed-by: kustomize
  name: gcpvmschedulerstartad-viewer-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartads/status
  verbs:
  - get
