//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartad) DeepCopyInto(out *GCPVMSchedulerStartad) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartad.
func (in *GCPVMSchedulerStartad) DeepCopy() *GCPVMSchedulerStartad {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartadList) DeepCopyInto(out *GCPVMSchedulerStartadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStartad, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartadList.
func (in *GCPVMSchedulerStartadList) DeepCopy() *GCPVMSchedulerStartadList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartadSpec) DeepCopyInto(out *GCPVMSchedulerStartadSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartadSpec.
func (in *GCPVMSchedulerStartadSpec) DeepCopy() *GCPVMSchedulerStartadSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartadStatus) DeepCopyInto(out *GCPVMSchedulerStartadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartadStatus.
func (in *GCPVMSchedulerStartadStatus) DeepCopy() *GCPVMSchedulerStartadStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopad) DeepCopyInto(out *GCPVMSchedulerStopad) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopad.
func (in *GCPVMSchedulerStopad) DeepCopy() *GCPVMSchedulerStopad {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopadList) DeepCopyInto(out *GCPVMSchedulerStopadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStopad, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopadList.
func (in *GCPVMSchedulerStopadList) DeepCopy() *GCPVMSchedulerStopadList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopadSpec) DeepCopyInto(out *GCPVMSchedulerStopadSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopadSpec.
func (in *GCPVMSchedulerStopadSpec) DeepCopy() *GCPVMSchedulerStopadSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopadStatus) DeepCopyInto(out *GCPVMSchedulerStopadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopadStatus.
func (in *GCPVMSchedulerStopadStatus) DeepCopy() *GCPVMSchedulerStopadStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopadStatus)
	in.DeepCopyInto(out)
	return out
}
